### ISSUE TITLE
Failed at the ProgressiveWordPress@0.0.3411 build script

### ISSUE THREAD

**Issue by ggPixel** [GoogleChrome/ProgressiveWordPress#27]
NodeJS version: 10.15.0
NPM version: 6.4.1
Running locally on WIndows 10

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ProgressiveWordPress@0.0.3411~prebuild: ProgressiveWordPress@0.0.3411
6 info lifecycle ProgressiveWordPress@0.0.3411~build: ProgressiveWordPress@0.0.3411
7 verbose lifecycle ProgressiveWordPress@0.0.3411~build: unsafe-perm in lifecycle true
8 verbose lifecycle ProgressiveWordPress@0.0.3411~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\christians\Desktop\wordpress-pwa\ProgressiveWordPress\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\System32\OpenSSH\;C:\wamp64\bin\php\php7.2.4;C:\Program Files\nodejs\;C:\Ruby22-x64\bin;C:\Users\christians\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\christians\AppData\Local\Programs\Python\Python36-32\;C:\Users\christians\AppData\Local\Microsoft\WindowsApps;C:\Users\christians\AppData\Roaming\Composer\vendor\bin;C:\Users\christians\AppData\Roaming\npm;C:\Program Files\Git\bin\;C:\Program Files\Git\cmd\
9 verbose lifecycle ProgressiveWordPress@0.0.3411~build: CWD: C:\Users\christians\Desktop\wordpress-pwa\ProgressiveWordPress
10 silly lifecycle ProgressiveWordPress@0.0.3411~build: Args: [ '/d /s /c',
10 silly lifecycle   'npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js' ]
11 silly lifecycle ProgressiveWordPress@0.0.3411~build: Returned: code: 1  signal: null
12 info lifecycle ProgressiveWordPress@0.0.3411~build: Failed to exec build script
13 verbose stack Error: ProgressiveWordPress@0.0.3411 build: `npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid ProgressiveWordPress@0.0.3411
15 verbose cwd C:\Users\christians\Desktop\wordpress-pwa\ProgressiveWordPress
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error ProgressiveWordPress@0.0.3411 build: `npm version --no-git-tag-version -f patch && mkdir -p dist; node build.js`
22 error Exit status 1
23 error Failed at the ProgressiveWordPress@0.0.3411 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ggPixel** [comment]
Never mind got this to work using the Docker method.

Thanks Surma, this web app is amazing!
